import type { Theme } from './types'

/**
 * The launch theme gallery (spec §13, themes 3–21). Each is a self-contained
 * token bundle — palette, accents, type, and card chrome — so the whole round
 * (lobby, live scoring, scorecards) restyles by switching the active bundle, with
 * zero component changes. `stat-sheet` (1) and `arcade` (2) live in their own
 * files; this module supplies the rest.
 *
 * `mode: 'fixed'` themes render the same regardless of the device's light/dark
 * preference, so an exported scorecard looks identical for everyone (spec §13).
 *
 * Display/label fonts name an intended typeface first and fall back to widely
 * available stacks — no web-font fetch, so themes stay offline-safe.
 */

const SANS = "'Inter', system-ui, sans-serif"
const SERIF = "'Georgia', 'Times New Roman', serif"
const MONO = "ui-monospace, 'SF Mono', 'Roboto Mono', monospace"
const TYPEWRITER = "'Courier New', Courier, monospace"
const HELVETICA = "'Helvetica Neue', Helvetica, Arial, sans-serif"
const HAND = "'Bradley Hand', 'Segoe Print', 'Comic Sans MS', cursive"
const IMPACT = "'Impact', 'Haettenschweiler', 'Arial Narrow', sans-serif"
const ORBITRON = "'Orbitron', 'Trebuchet MS', sans-serif"
const BANGERS = "'Bangers', 'Comic Sans MS', sans-serif"

export const galleryThemes: Theme[] = [
  {
    id: 'vintage',
    name: 'Vintage',
    description:
      'Cream course scorecard; serif labels, typewriter numerals, tan grid; winner = rubber stamp.',
    mode: 'light',
    tokens: {
      '--color-bg': '#f4ecd8',
      '--color-surface': '#fbf6e9',
      '--color-surface-alt': '#ece0c4',
      '--color-text': '#3b2f1e',
      '--color-muted': '#8a7a5c',
      '--color-border': '#d8c7a0',
      '--color-accent': '#8c4b2f',
      '--color-accent-contrast': '#fbf6e9',
      '--color-winner': '#6b8e23',
      '--font-label': SERIF,
      '--font-numeral': TYPEWRITER,
      '--font-display': SERIF,
      '--radius-card': '0.375rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard',
    description:
      'Slate-green board, chalk-style type, hand-drawn feel; winner = circled in chalk.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#1f2d28',
      '--color-surface': '#25342f',
      '--color-surface-alt': '#2f413b',
      '--color-text': '#eef3ee',
      '--color-muted': '#9bb0a6',
      '--color-border': '#41544d',
      '--color-accent': '#f4e7c1',
      '--color-accent-contrast': '#1f2d28',
      '--color-winner': '#ffd966',
      '--font-label': HAND,
      '--font-numeral': MONO,
      '--font-display': HAND,
      '--radius-card': '0.25rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description:
      'Deep navy with white/cyan technical line-work, monospace, grid; winner = boxed callout.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#0d2440',
      '--color-surface': '#103057',
      '--color-surface-alt': '#15406f',
      '--color-text': '#e8f4ff',
      '--color-muted': '#7fa8d0',
      '--color-border': '#2f6aa8',
      '--color-accent': '#5fd0ff',
      '--color-accent-contrast': '#06192e',
      '--color-winner': '#ffffff',
      '--font-label': MONO,
      '--font-numeral': MONO,
      '--font-display': MONO,
      '--radius-card': '0.125rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'receipt',
    name: 'Receipt',
    description:
      'Narrow thermal-printer look, monospace, dashed tear lines, "TOTAL" styling; winner = starred.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#f3f1ea',
      '--color-surface': '#ffffff',
      '--color-surface-alt': '#ececec',
      '--color-text': '#1a1a1a',
      '--color-muted': '#777777',
      '--color-border': '#cccccc',
      '--color-accent': '#1a1a1a',
      '--color-accent-contrast': '#ffffff',
      '--color-winner': '#1a1a1a',
      '--font-label': MONO,
      '--font-numeral': MONO,
      '--font-display': MONO,
      '--radius-card': '0rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description:
      'CRT black with phosphor-green monospace, ASCII frame; winner = "> WINNER" line.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#010d03',
      '--color-surface': '#02160a',
      '--color-surface-alt': '#053314',
      '--color-text': '#39ff14',
      '--color-muted': '#1f9a1f',
      '--color-border': '#0f5f1f',
      '--color-accent': '#39ff14',
      '--color-accent-contrast': '#010d03',
      '--color-winner': '#aaff66',
      '--font-label': MONO,
      '--font-numeral': MONO,
      '--font-display': MONO,
      '--radius-card': '0rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'newsprint',
    name: 'Newsprint',
    description:
      'Black-and-white serif tabloid, halftone texture; winner = headline.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#eceae3',
      '--color-surface': '#f7f6f1',
      '--color-surface-alt': '#dddbd3',
      '--color-text': '#111111',
      '--color-muted': '#555555',
      '--color-border': '#999999',
      '--color-accent': '#111111',
      '--color-accent-contrast': '#f7f6f1',
      '--color-winner': '#b3001b',
      '--font-label': SERIF,
      '--font-numeral': SERIF,
      '--font-display': SERIF,
      '--radius-card': '0rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'trail',
    name: 'Trail',
    description:
      'Outdoorsy kraft + forest green, topographic contour lines; winner = wooden trail-sign badge.',
    mode: 'light',
    tokens: {
      '--color-bg': '#efe6d2',
      '--color-surface': '#f7f1e3',
      '--color-surface-alt': '#e3d6b8',
      '--color-text': '#2f3b25',
      '--color-muted': '#6f7a55',
      '--color-border': '#c8b78c',
      '--color-accent': '#3f6f3f',
      '--color-accent-contrast': '#f7f1e3',
      '--color-winner': '#b5651d',
      '--font-label': SANS,
      '--font-numeral': MONO,
      '--font-display': SERIF,
      '--radius-card': '0.5rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'casino-felt',
    name: 'Casino felt',
    description:
      'Green felt + gold, poker-chip motif (a nod to the side-bet origin); winner = gold chip.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#0b3d2e',
      '--color-surface': '#0f4a37',
      '--color-surface-alt': '#155a43',
      '--color-text': '#f5f0e1',
      '--color-muted': '#b8c9b8',
      '--color-border': '#c0a062',
      '--color-accent': '#d4af37',
      '--color-accent-contrast': '#0b3d2e',
      '--color-winner': '#ffd700',
      '--font-label': SERIF,
      '--font-numeral': MONO,
      '--font-display': SERIF,
      '--radius-card': '0.75rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'comic-pop',
    name: 'Comic pop',
    description:
      'Bold panel with thick black borders and Ben-Day dots; winner = burst graphic.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#fff8e1',
      '--color-surface': '#ffffff',
      '--color-surface-alt': '#ffe680',
      '--color-text': '#111111',
      '--color-muted': '#555555',
      '--color-border': '#111111',
      '--color-accent': '#e60000',
      '--color-accent-contrast': '#ffffff',
      '--color-winner': '#1565c0',
      '--font-label': BANGERS,
      '--font-numeral': HELVETICA,
      '--font-display': BANGERS,
      '--radius-card': '0.5rem',
      '--border-width-card': '3px',
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    description:
      'Outrun sunset in flat magenta/orange bands, chrome display type, neon grid; winner = hot-magenta block.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#1a0b2e',
      '--color-surface': '#2a1145',
      '--color-surface-alt': '#3a1a5c',
      '--color-text': '#ffe6ff',
      '--color-muted': '#b07fd0',
      '--color-border': '#7a2f8a',
      '--color-accent': '#ff2bd6',
      '--color-accent-contrast': '#1a0b2e',
      '--color-winner': '#ffb347',
      '--font-label': SANS,
      '--font-numeral': MONO,
      '--font-display': ORBITRON,
      '--radius-card': '0.25rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    description:
      'Stark black on white, oversized Helvetica, heavy rules, asymmetric; winner = giant black bar.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#ffffff',
      '--color-surface': '#ffffff',
      '--color-surface-alt': '#f0f0f0',
      '--color-text': '#000000',
      '--color-muted': '#444444',
      '--color-border': '#000000',
      '--color-accent': '#000000',
      '--color-accent-contrast': '#ffffff',
      '--color-winner': '#ff3b00',
      '--font-label': HELVETICA,
      '--font-numeral': HELVETICA,
      '--font-display': HELVETICA,
      '--radius-card': '0rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'zine',
    name: 'Zine',
    description:
      'Punk photocopy, high-contrast b&w + one spot color, ransom-note/cut-paper type; winner = scrawled.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#e8e6e1',
      '--color-surface': '#f5f4f0',
      '--color-surface-alt': '#d8d6d0',
      '--color-text': '#111111',
      '--color-muted': '#555555',
      '--color-border': '#111111',
      '--color-accent': '#ff2d55',
      '--color-accent-contrast': '#ffffff',
      '--color-winner': '#111111',
      '--font-label': TYPEWRITER,
      '--font-numeral': MONO,
      '--font-display': IMPACT,
      '--radius-card': '0rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    description:
      'White photo borders, handwritten captions, washi-tape accents; winner = "winner!" sticker.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#efeae3',
      '--color-surface': '#ffffff',
      '--color-surface-alt': '#f3ede2',
      '--color-text': '#2b2b2b',
      '--color-muted': '#8a8275',
      '--color-border': '#e0d8c8',
      '--color-accent': '#2bb3a3',
      '--color-accent-contrast': '#ffffff',
      '--color-winner': '#e58a2a',
      '--font-label': HAND,
      '--font-numeral': SANS,
      '--font-display': HAND,
      '--radius-card': '0.25rem',
      '--border-width-card': '6px',
    },
  },
  {
    id: 'noir',
    name: 'Noir',
    description:
      'High-contrast film-noir b&w, venetian-blind motif, typewriter; winner = "case closed" stamp.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#0d0d0f',
      '--color-surface': '#16161a',
      '--color-surface-alt': '#1f1f24',
      '--color-text': '#f2f2f2',
      '--color-muted': '#9a9aa0',
      '--color-border': '#3a3a42',
      '--color-accent': '#d9d9d9',
      '--color-accent-contrast': '#0d0d0f',
      '--color-winner': '#c8a13a',
      '--font-label': TYPEWRITER,
      '--font-numeral': TYPEWRITER,
      '--font-display': TYPEWRITER,
      '--radius-card': '0rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'spreadsheet',
    name: 'Spreadsheet',
    description:
      'Deadpan corporate; green-bar cells, plain sans, "Q3 results"; winner = conditional-format green cell.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#ffffff',
      '--color-surface': '#ffffff',
      '--color-surface-alt': '#e6efe6',
      '--color-text': '#1a1a1a',
      '--color-muted': '#6b7280',
      '--color-border': '#c9d2c9',
      '--color-accent': '#217346',
      '--color-accent-contrast': '#ffffff',
      '--color-winner': '#2ea043',
      '--font-label': "'Calibri', 'Segoe UI', system-ui, sans-serif",
      '--font-numeral': "'Calibri', 'Segoe UI', system-ui, sans-serif",
      '--font-display': "'Calibri', 'Segoe UI', system-ui, sans-serif",
      '--radius-card': '0.125rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    description:
      'Deep-space navy/purple, starfield, constellation lines; winner = supernova mark.',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#0a0e2a',
      '--color-surface': '#121845',
      '--color-surface-alt': '#1b2360',
      '--color-text': '#eaeaff',
      '--color-muted': '#9aa0d0',
      '--color-border': '#2f3a8a',
      '--color-accent': '#8a7bff',
      '--color-accent-contrast': '#0a0e2a',
      '--color-winner': '#ffd166',
      '--font-label': SANS,
      '--font-numeral': MONO,
      '--font-display': ORBITRON,
      '--radius-card': '0.5rem',
      '--border-width-card': '1px',
    },
  },
  {
    id: 'pinball',
    name: 'Pinball',
    description:
      'Backglass styling, bright primaries, bumper/score-reel motifs; winner = "JACKPOT".',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#1a1030',
      '--color-surface': '#241644',
      '--color-surface-alt': '#33205f',
      '--color-text': '#fff7e6',
      '--color-muted': '#c2a0e0',
      '--color-border': '#ff5d8f',
      '--color-accent': '#ffd400',
      '--color-accent-contrast': '#1a1030',
      '--color-winner': '#ff3b3b',
      '--font-label': SANS,
      '--font-numeral': MONO,
      '--font-display': BANGERS,
      '--radius-card': '0.5rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'tiki',
    name: 'Tiki',
    description:
      'Warm beach sunset, bamboo frame, palm/tiki motifs; winner = lei/flower.',
    mode: 'light',
    tokens: {
      '--color-bg': '#ffe8c7',
      '--color-surface': '#fff3df',
      '--color-surface-alt': '#ffd9a0',
      '--color-text': '#5b3a1e',
      '--color-muted': '#9c7a52',
      '--color-border': '#d8a86a',
      '--color-accent': '#e2632a',
      '--color-accent-contrast': '#fff3df',
      '--color-winner': '#2f8f6b',
      '--font-label': SANS,
      '--font-numeral': MONO,
      '--font-display': "'Trebuchet MS', 'Segoe UI', sans-serif",
      '--radius-card': '0.75rem',
      '--border-width-card': '2px',
    },
  },
  {
    id: 'bowling',
    name: 'Bowling',
    description:
      'Cosmic-lane score sheet, retro frame grid; winner = strike "X".',
    mode: 'fixed',
    tokens: {
      '--color-bg': '#101a3a',
      '--color-surface': '#16224a',
      '--color-surface-alt': '#20305f',
      '--color-text': '#f3f6ff',
      '--color-muted': '#9fb0d8',
      '--color-border': '#34538c',
      '--color-accent': '#ff7a00',
      '--color-accent-contrast': '#101a3a',
      '--color-winner': '#ffd23f',
      '--font-label': SANS,
      '--font-numeral': MONO,
      '--font-display': "'Trebuchet MS', 'Segoe UI', sans-serif",
      '--radius-card': '0.375rem',
      '--border-width-card': '1px',
    },
  },
]
